name = "Zyra AI"
client_id = "c09a80c1af36e5ae2643ad5088b1025f"
application_url = "https://zzyraai.com"
embedded = false

[access_scopes]
scopes = "read_products,write_products,read_product_listings,read_orders,read_customers,write_customers,read_inventory,write_inventory,read_fulfillments,write_fulfillments,read_locations,read_themes,write_themes,read_script_tags,write_script_tags,read_analytics,read_marketing_events,write_marketing_events,read_price_rules,write_price_rules,read_discounts,write_discounts"

[auth]
redirect_urls = ["https://zzyraai.com/api/shopify/callback"]

[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://zzyraai.com/api/webhooks/shopify/app_uninstalled"

[[webhooks.subscriptions]]
topics = ["products/create", "products/update", "products/delete"]
uri = "https://zzyraai.com/api/webhooks/shopify/products"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://zzyraai.com/api/webhooks/compliance"
